/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See https://github.com/openMF/mifos-x-field-officer-app/blob/master/LICENSE.md
 */
package com.mifos.room.entities.report

import androidx.room3.Entity
import androidx.room3.Index
import androidx.room3.PrimaryKey
import kotlinx.serialization.Serializable

/**
 * Flattened Room row for a single run-report category-list item.
 *
 * The Fineract network payload (`com.mifos.core.model.objects.runreport.client.ClientReportTypeItem`)
 * is already flat — every field is a nullable scalar — so it maps 1:1 onto Room columns with no
 * nested objects to unpack. Following this fork's Store5 house style (see `CheckerTaskEntity` /
 * `LoanTransactionEntity`), the domain shape is persisted verbatim so the cached list round-trips
 * back into `ClientReportTypeItem` for the `RunReportScreen` (which renders `reportName`,
 * `reportType`, `reportCategory` and passes the whole item to `onReportClick`, so every field is
 * kept for a clean round-trip).
 *
 * ### Composite scoping — NOT a natural key
 * The category list is scoped server-side by the request tuple
 * `(reportCategory, genericResultSet, parameterType)` — the SAME three params the Store key carries.
 * Those columns are denormalized onto every row so the SoT reader can filter by the key. No field of
 * the payload is a stable unique identifier (`reportId` is nullable and can repeat across scopes), so
 * the primary key is an autogenerated [rowId] and the scoping tuple is indexed for the reader query.
 */
@Entity(
    tableName = "report_categories",
    indices = [Index(value = ["reportCategory", "genericResultSet", "parameterType"])],
)
@Serializable
data class ReportCategoryEntity(
    @PrimaryKey(autoGenerate = true)
    val rowId: Long = 0,

    // --- scoping columns (the Store key tuple, denormalized onto each row) ---
    val reportCategory: String,

    val genericResultSet: Boolean,

    val parameterType: Boolean,

    // --- ClientReportTypeItem payload (persisted verbatim for a clean round-trip) ---
    val parameterId: Int? = null,

    val parameterName: String? = null,

    val itemReportCategory: String? = null,

    val reportId: Int? = null,

    val reportName: String? = null,

    val reportParameterName: String? = null,

    val reportSubtype: String? = null,

    val reportType: String? = null,
)
