/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See https://github.com/openMF/mifos-x-field-officer-app/blob/master/LICENSE.md
 */
@file:OptIn(
    androidx.compose.material3.ExperimentalMaterial3Api::class,
    kotlin.time.ExperimentalTime::class,
)

package com.mifos.feature.loan.newLoanAccount.pages

import androidclient.feature.loan.generated.resources.Res
import androidclient.feature.loan.generated.resources.back
import androidclient.feature.loan.generated.resources.feature_loan_cancel
import androidclient.feature.loan.generated.resources.feature_loan_charge_submit
import androidclient.feature.loan.generated.resources.feature_loan_dialog_action_ok
import androidclient.feature.loan.generated.resources.next
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.DatePicker
import androidx.compose.material3.DatePickerDialog
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.rememberDatePickerState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableLongStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.sp
import com.mifos.core.common.utils.DateHelper
import com.mifos.core.designsystem.component.MifosDatePickerTextField
import com.mifos.core.designsystem.component.MifosOutlinedTextField
import com.mifos.core.designsystem.component.MifosTextFieldDropdown
import com.mifos.core.ui.components.MifosTwoButtonRow
import com.mifos.feature.loan.newLoanAccount.NewLoanAccountAction
import com.mifos.room.entities.noncore.ColumnHeader
import com.mifos.room.entities.noncore.DataTableEntity
import org.jetbrains.compose.resources.stringResource
import template.core.base.designsystem.theme.KptTheme
import kotlin.time.Clock

/**
 * Inline per-datatable step inside the loan-creation stepper.
 *
 * Renders a fully-dynamic form derived from [DataTableEntity.columnHeaderData].
 * Skips system columns:
 *   - `columnPrimaryKey == true` (auto-generated loan_id)
 *   - column name in `created_at` / `updated_at` (audit timestamps)
 *
 * Per-column widget choice keyed on `columnDisplayType` (matches Fineract
 * `ResultsetColumnHeaderData.ColumnDisplayType` enum, which the mapper writes as
 * the uppercase string). CODELOOKUP/CODEVALUE dropdowns are populated from
 * `columnValues` returned per column in the SAME response — no separate fetch.
 *
 * The picked-id (not display string) is persisted for CODELOOKUP columns —
 * Fineract expects code ids in the submit payload.
 *
 * @param table       the datatable schema for this step
 * @param values      current values keyed by column name (lifted to ViewModel)
 * @param onValueChange emits a typed [DatatableFieldValue] per user edit
 */

@Composable
fun DatatableStepPage(
    table: DataTableEntity,
    values: Map<String, DatatableFieldValue>,
    onValueChange: (columnName: String, value: DatatableFieldValue) -> Unit,
    onAction: (NewLoanAccountAction) -> Unit,
    isLastStep: Boolean,
    modifier: Modifier = Modifier,
) {
    val scrollState = rememberScrollState()

    Column(
        modifier = modifier
            .fillMaxWidth()
            .verticalScroll(scrollState)
            .padding(horizontal = KptTheme.spacing.md, vertical = KptTheme.spacing.md),
    ) {
        Text(
            text = table.registeredTableName ?: "",
            fontWeight = FontWeight.Bold,
            fontSize = 18.sp,
        )
        Spacer(modifier = Modifier.height(KptTheme.spacing.md))

        table.columnHeaderData
            .filter { header -> header.isNotAutoGeneratedOrNull() }
            .forEach { header ->
                DatatableField(
                    header = header,
                    currentValue = values[header.dataTableColumnName],
                    onValueChange = { v ->
                        header.dataTableColumnName?.let { onValueChange(it, v) }
                    },
                )
            }

        Spacer(modifier = Modifier.height(KptTheme.spacing.md))

        MifosTwoButtonRow(
            firstBtnText = stringResource(Res.string.back),
            secondBtnText = stringResource(
                if (isLastStep) Res.string.feature_loan_charge_submit else Res.string.next,
            ),
            onFirstBtnClick = { onAction(NewLoanAccountAction.PreviousStep) },
            onSecondBtnClick = {
                if (isLastStep) {
                    onAction(NewLoanAccountAction.SubmitLoanApplication)
                } else {
                    onAction(NewLoanAccountAction.NextStep)
                }
            },
        )
    }
}

/**
 * Columns Fineract auto-fills on insert — never user input.
 *  - `created_at` / `updated_at` : audit timestamps.
 *  - `loan_id` / `client_id` / etc: foreign key to the parent entity.
 *  Visible in the API response because the schema is flat,
 *  but the backend populates the Foreign Key from the parent on POST.
 *
 * Product 1's INSTITUCION_FINANCIERA datatable surfaces a `loan_id` column
 * with `isColumnPrimaryKey: false`, so the Primary Key filter alone is
 * insufficient. Web-app strips these by name; we do the same.
 */
private val SYSTEM_COLUMNS = setOf(
    "created_at", "updated_at", "createdAt", "updatedAt",
    "loan_id", "client_id", "group_id", "savings_id", "share_id", "office_id",
)

private fun ColumnHeader.isNotAutoGeneratedOrNull(): Boolean {
    val name = dataTableColumnName ?: return false
    return columnPrimaryKey == false && name !in SYSTEM_COLUMNS
}

private fun ColumnHeader.displayLabel(): String {
    val name = this.dataTableColumnName ?: return ""
    if ("_cd_" !in name) return name
    return name.substringBefore("_cd_")
}

@Composable
private fun DatatableField(
    header: ColumnHeader,
    currentValue: DatatableFieldValue?,
    onValueChange: (DatatableFieldValue) -> Unit,
) {
    val label = header.displayLabel().ifBlank { return }

    when (header.columnDisplayType) {
        "STRING" -> TextFieldRow(
            value = (currentValue as? DatatableFieldValue.Text)?.text.orEmpty(),
            onValueChange = { onValueChange(DatatableFieldValue.Text(it)) },
            label = label,
            keyboardType = KeyboardType.Text,
            singleLine = true,
        )

        "TEXT" -> TextFieldRow(
            value = (currentValue as? DatatableFieldValue.Text)?.text.orEmpty(),
            onValueChange = { onValueChange(DatatableFieldValue.Text(it)) },
            label = label,
            keyboardType = KeyboardType.Text,
            singleLine = false,
        )

        "INTEGER" -> TextFieldRow(
            value = (currentValue as? DatatableFieldValue.Text)?.text.orEmpty(),
            onValueChange = { onValueChange(DatatableFieldValue.Text(it)) },
            label = label,
            keyboardType = KeyboardType.Number,
            singleLine = true,
        )

        "DECIMAL", "FLOAT" -> TextFieldRow(
            value = (currentValue as? DatatableFieldValue.Text)?.text.orEmpty(),
            onValueChange = { onValueChange(DatatableFieldValue.Text(it)) },
            label = label,
            keyboardType = KeyboardType.Decimal,
            singleLine = true,
        )

        "DATE" -> DateFieldRow(
            label = label,
            currentValue = (currentValue as? DatatableFieldValue.Text)?.text,
            onDateSelected = { onValueChange(DatatableFieldValue.Text(it)) },
        )

        "BOOLEAN" -> BooleanFieldRow(
            label = label,
            currentValue = (currentValue as? DatatableFieldValue.Bool)?.checked ?: false,
            onValueChange = { onValueChange(DatatableFieldValue.Bool(it)) },
        )

        "CODELOOKUP", "CODEVALUE" -> DropdownFieldRow(
            label = label,
            header = header,
            currentId = (currentValue as? DatatableFieldValue.Code)?.id,
            onIdSelected = { onValueChange(DatatableFieldValue.Code(it)) },
        )

        else -> Unit
    }
}

@Composable
private fun TextFieldRow(
    value: String,
    onValueChange: (String) -> Unit,
    label: String,
    keyboardType: KeyboardType,
    singleLine: Boolean,
) {
    MifosOutlinedTextField(
        value = value,
        onValueChange = onValueChange,
        label = label,
        keyboardType = keyboardType,
        singleLine = singleLine,
        maxLines = if (singleLine) 1 else 5,
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = KptTheme.spacing.sm),
    )
}

@Composable
private fun DateFieldRow(
    label: String,
    currentValue: String?,
    onDateSelected: (String) -> Unit,
) {
    var showDatePicker by rememberSaveable(label) { mutableStateOf(false) }
    var selectedMillis by rememberSaveable(label) {
        mutableLongStateOf(Clock.System.now().toEpochMilliseconds())
    }
    val datePickerState = rememberDatePickerState(initialSelectedDateMillis = selectedMillis)

    if (showDatePicker) {
        DatePickerDialog(
            onDismissRequest = { showDatePicker = false },
            confirmButton = {
                TextButton(onClick = {
                    showDatePicker = false
                    datePickerState.selectedDateMillis?.let { millis ->
                        selectedMillis = millis
                        onDateSelected(DateHelper.getDateAsStringFromLong(millis))
                    }
                }) { Text(stringResource(Res.string.feature_loan_dialog_action_ok)) }
            },
            dismissButton = {
                TextButton(onClick = { showDatePicker = false }) {
                    Text(stringResource(Res.string.feature_loan_cancel))
                }
            },
        ) {
            DatePicker(state = datePickerState)
        }
    }

    MifosDatePickerTextField(
        value = currentValue ?: "",
        label = label,
        openDatePicker = { showDatePicker = true },
    )
    Spacer(modifier = Modifier.height(KptTheme.spacing.sm))
}

@Composable
private fun BooleanFieldRow(
    label: String,
    currentValue: Boolean,
    onValueChange: (Boolean) -> Unit,
) {
    Row(
        verticalAlignment = Alignment.CenterVertically,
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = KptTheme.spacing.sm),
    ) {
        Text(text = label, modifier = Modifier.weight(1f))
        Switch(
            checked = currentValue,
            onCheckedChange = onValueChange,
        )
    }
}

@Composable
private fun DropdownFieldRow(
    label: String,
    header: ColumnHeader,
    currentId: Int?,
    onIdSelected: (Int) -> Unit,
) {
    val filteredPairs = remember(header) {
        header.columnValues.mapNotNull { cv -> cv.value?.let { v -> cv.id to v } }
    }
    val options = filteredPairs.map { it.second }
    val currentDisplay = remember(currentId, filteredPairs) {
        currentId?.let { id -> filteredPairs.firstOrNull { it.first == id }?.second }.orEmpty()
    }

    Box(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = KptTheme.spacing.sm),
    ) {
        MifosTextFieldDropdown(
            value = currentDisplay,
            onValueChanged = {},
            label = label,
            modifier = Modifier.fillMaxWidth(),
            readOnly = true,
            options = options,
            onOptionSelected = { index, _ ->
                filteredPairs.getOrNull(index)?.first?.let { onIdSelected(it) }
            },
        )
    }
}
