/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.database

import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import kpt.core.base.database.infra.dao.BookkeeperDao
import kpt.core.base.database.infra.dao.DraftDao
import kpt.core.base.database.infra.dao.FetchedAtDao
import kpt.core.base.database.infra.entity.BookkeeperEntity
import kpt.core.base.database.infra.entity.DraftEntity
import kpt.core.base.database.infra.entity.FetchedAtEntity

/**
 * KSP-generated constructor bridge for [AppDatabase].
 *
 * Room 3 requires an `expect object` annotated via [@ConstructedBy][ConstructedBy] so that
 * the KSP compiler plugin can generate a platform-specific `actual object` containing the
 * `AppDatabase_Impl` instantiation logic.
 */
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}

/**
 * Root Room 3 database for the application.
 *
 * This is a **commonMain** definition that works across all Kotlin Multiplatform targets
 * (Android, Desktop/JVM, iOS/Native, JS, WasmJS). Platform-specific database creation
 * is handled by [kpt.core.base.database.AppDatabaseFactory] in each platform's
 * DI module — see [kpt.core.database.di.DatabaseModule].
 *
 * Room 3 uses the [ConstructedBy] annotation to delegate instance creation to
 * [AppDatabaseConstructor], whose `actual` implementation is generated by KSP on
 * every target.
 *
 * ## Demo demarcation (showcase-framework-separation)
 * The `infra` entities/DAOs (`Bookkeeper·Draft·FetchedAt`) are framework — always kept.
 * The demo entities/DAOs/converters + the `@AutoMigration` history + the `@DeleteTable`
 * spec are wrapped in demo-marked blocks. `customizer --clean`
 * deletes the `core/database/demo/` packages AND strips these blocks (and resets `VERSION` to a
 * fresh-fork baseline of `1`, dropping the migration history that only existing installs
 * need) — leaving a valid framework-only `@Database` that compiles. The Room 3 impl itself
 * is unchanged; the markers are comments and are behavior-neutral until stripped.
 *
 * ## Schema history
 * | Version | Change |
 * |---------|--------|
 * | v3 → v4 | adds `framework_fetched_at` |
 * | v4 → v5 | adds `framework_submit_drafts` |
 * | v5 → v6 | adds `personal_watchlist` |
 * | v6 → v7 | adds `uniqueKey` column to drafts |
 * | v7 → v8 | adds `banking_loans` + `banking_bill_reminders` |
 * | v8 → v10 | adds `alerts` + `interest_rate_series`; drops `samples` ([MigrationSpec8to10]) |
 */
@Database(
    entities = [
        // infra (framework) — always kept
        BookkeeperEntity::class,
        FetchedAtEntity::class,
        DraftEntity::class,
        // demo:begin/demo:end block removed (offline-first-template-migration 01-template-adoption
        // T-AC3-merge): the demo entities/DAOs/converters this fork never carried a
        // `core/database/demo/**` tree for (never synced in — customizer --clean was never run on
        // this legacy fork, so this file was the one dangling reference left behind). Stripped by
        // hand, matching exactly what `customizer --clean` documents doing per this file's own
        // "Demo demarcation" doc comment above.
        // fork:begin — a fork adds its OWN @Entity classes here. This block is PRESERVED across
        // /kmp-project-template-sync; never add entities outside it. For each schema-changing fork
        // entity, bump ForkDatabaseConfig.VERSION_OFFSET and add a matching AutoMigration in the fork
        // block below. Kept in its own region so fork + template entity additions never share a merge
        // hunk (conflict-free adoption).
        // fork:end
    ],
    version = AppDatabase.VERSION,
    exportSchema = true,
    autoMigrations = [
        // demo:begin/demo:end autoMigrations + @DeleteTable spec removed alongside the entities
        // above — see the entities-list comment for rationale.
        // fork:begin — a fork adds its own AutoMigration(...) entries here, one per schema-changing
        // fork entity (from = previous effective version, to = new). PRESERVED across sync.
        // fork:end
    ],
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {

    // infra (framework) — always kept
    abstract val bookkeeperDao: BookkeeperDao
    abstract val fetchedAtDao: FetchedAtDao
    abstract val draftDao: DraftDao

    // demo:begin/demo:end DAO accessors + MigrationSpec8to10 removed alongside the entities above.

    // fork:begin — a fork adds its own `abstract val fooDao: FooDao` accessors here. PRESERVED
    // across /kmp-project-template-sync; kept in its own region so fork + template DAO additions
    // never share a merge hunk.
    // fork:end

    companion object {
        // `customizer --clean` resets TEMPLATE_BASE_VERSION to 1 (fresh-fork baseline) since the
        // demo migration history is stripped with the demo block — done by hand here (see the
        // entities-list comment above for why this fork does it post-hoc).
        /** Template-owned base schema version — the TEMPLATE bumps this on its own schema changes. */
        const val TEMPLATE_BASE_VERSION = 1

        /**
         * Effective DB schema version = template base + the fork's offset ([ForkDatabaseConfig],
         * fork-owned). A fork bumping its schema edits `VERSION_OFFSET` in its own file, never this
         * base — so fork and template version bumps never collide on the same line (conflict-free
         * adoption). Both operands are `const`, so this stays a compile-time constant Room accepts.
         */
        const val VERSION = TEMPLATE_BASE_VERSION + ForkDatabaseConfig.VERSION_OFFSET

        /** Fork-unique on-disk DB filename — single source of truth is [DatabaseConfig.NAME]
         *  (appId-derived, regenerated by `syncForkConfig`). All platform builders read this. */
        const val DATABASE_NAME = DatabaseConfig.NAME
    }
}
